services:
  - type: web
    name: wisdomafrican-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_token_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
